const products = [
  {
    _id: '1',
    name: 'The Longest Echo: A Novel',
    author: 'Eoin Dempsey',
    image: '/images/Book_001.png',
    description:
      'Occupied Italy, 1944. In the mountain regions south of Bologna, Liliana Nicoletti’s family finds escaped POW James Foley behind German lines. Committed to the anti-Fascist cause, they deliver him to a powerful band of local partisans. But when the SS launches a brutal attack against the Resistance, Liliana’s peaceful community is destroyed. Alone and thrown together by tragedy, James and Liliana fight together as Monte Sole burns. Forging an unbreakable bond, they know their only hope of survival is to make it to the Allied lines.',
    ASIN: 'B088JRPPY9',
    category: 'Novel',
    Publisher: 'Lake Union Publishing (9 February 2021)',
    Language: 'English',
    price: 9.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 122,
  },
  {
    _id: '2',
    name: 'The Survivors',
    author: 'Jane Harper',
    image: '/images/Book_002.png',
    description:
      "Kieran Elliott's life changed forever on the day a reckless mistake led to devastating consequences.The guilt that still haunts him resurfaces during a visit with his young family to the small coastal community he once called home. Kieran's parents are struggling in a town where fortunes are forged by the sea. Between them all is his absent brother, Finn. When a body is discovered on the beach, long-held secrets threaten to emerge. A sunken wreck, a missing girl, and questions that have never washed away...",
    ASIN: 'B087WP479H',
    category: 'Novel',
    Publisher: 'Macmillan Australia (22 September 2020)',
    Language: 'English',
    price: 7.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 1260,
  },
  {
    _id: '3',
    name: "The Bigamist: The True Story of a Husband's Ultimate Betrayal",
    author: 'Mary Turner Thomson',
    image: '/images/Book_003.png',
    description:
      'When Mary met Will Jordan online, she was a single mother who’d given up trying to find Mr Right. And yet here he suddenly was: articulate and attractive, with a fascinating background. Soon they were in love, and when he proposed after a month it seemed recklessly romantic.',
    ASIN: 'B085CHRSG4',
    category: 'Novel',
    Publisher: 'Little A (15 September 2020)',
    Language: 'English',
    price: 4.5,
    countInStock: 27,
    rating: 1,
    numReviews: 3760,
  },
  {
    _id: '4',
    name: 'When He Was Wicked: Bridgerton (Bridgertons Book 6)',
    author: 'Julia Quinn',
    image: '/images/Book_004.png',
    description:
      "A moment so tremendous, so sharp and breathtaking, that one knows one's life will never be the same. For Michael Stirling, London's most infamous rake, that moment came the first time he laid eyes on Francesca Bridgerton.",
    ASIN: 'B00UG8RP9U',
    category: 'Novel',
    Publisher: 'Avon; Reprint edition (28 February 2017)',
    Language: 'English',
    price: 4.5,
    countInStock: 9,
    rating: 4.5,
    numReviews: 2410,
  },
  {
    _id: '5',
    name: 'To Sir Phillip, With Love: Bridgerton (Bridgertons Book 5)',
    author: 'Julia Quinn',
    image: '/images/Book_005.png',
    description:
      'Sir Phillip knew that Eloise Bridgerton was a spinster, and so he’d proposed, figuring that she’d be homely and unassuming, and more than a little desperate for an offer of marriage. Except . . . she wasn’t. The beautiful woman on his doorstep was anything but quiet, and when she stopped talking long enough to close her mouth, all he wanted to do was kiss her ',
    ASIN: 'B00U6SFUVK',
    category: 'Novel',
    Publisher: 'Avon; Reprint edition (31 January 2017)',
    Language: 'English',
    price: 3.99,
    countInStock: 0,
    rating: 4.5,
    numReviews: 5410,
  },
  {
    _id: '6',
    name: 'To Sir Phillip, With Love: Bridgerton (Bridgertons Book 5)',
    author: 'Julia Quinn',
    image: '/images/Book_005.png',
    description:
      'Sir Phillip knew that Eloise Bridgerton was a spinster, and so he’d proposed, figuring that she’d be homely and unassuming, and more than a little desperate for an offer of marriage. Except . . . she wasn’t. The beautiful woman on his doorstep was anything but quiet, and when she stopped talking long enough to close her mouth, all he wanted to do was kiss her ',
    ASIN: 'B00U6SFUVK',
    category: 'Novel',
    Publisher: 'Avon; Reprint edition (31 January 2017)',
    Language: 'English',
    price: 3.99,
    countInStock: 9,
    rating: 4.5,
    numReviews: 5410,
  },
  {
    _id: '7',
    name: 'To Sir Phillip, With Love: Bridgerton (Bridgertons Book 5)',
    author: 'Julia Quinn',
    image: '/images/Book_005.png',
    description:
      'Sir Phillip knew that Eloise Bridgerton was a spinster, and so he’d proposed, figuring that she’d be homely and unassuming, and more than a little desperate for an offer of marriage. Except . . . she wasn’t. The beautiful woman on his doorstep was anything but quiet, and when she stopped talking long enough to close her mouth, all he wanted to do was kiss her ',
    ASIN: 'B00U6SFUVK',
    category: 'Novel',
    Publisher: 'Avon; Reprint edition (31 January 2017)',
    Language: 'English',
    price: 3.99,
    countInStock: 9,
    rating: 4.5,
    numReviews: 5410,
  },
];

export default products;
